baseURL = 'https://ciana-linm.com/'  
languageCode = 'en-us'
title = 'CIANA LIN MENG'
theme = 'PaperMod'

# 首页设置
[pagination]
  pagerSize = 10
summaryLength = 30

[params]
  author = "Ciana Linmeng"
  defaultTheme = "light"
  ShowShareButtons = false
  ShowReadingTime = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  homeInfoParams = false
  hideSummary = true
  hideMeta = true
  disableThemeToggle = true
  disableScrollToTop = true

  homeInfoMode = "ShowAll"
  mainSections = ["posts"]

  # 封面设置
  [params.cover]
    hidden = false
    hiddenInList = false
    hiddenInSingle = false
    responsiveImages = true

# 菜单设置
# 菜单设置
[menu]
  [[menu.main]]
    name = "Works"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Carnet"
    url = "/carnet/"
    weight = 2

  [[menu.main]]
    name = "Fragments"
    url = "/fragments/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true