baseURL = 'https://ciana-linm.com/'  
languageCode = 'en-us'
title = 'Ciana Lin Meng'
theme = 'PaperMod'

# 首页设置
[pagination]
  pagerSize = 10
summaryLength = 30

[params]
  author = "Ciana Linmeng"
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  homeInfoParams = false
  hideSummary = false
  hideMeta = false

  # ✅ 这两行是关键
  homeInfoMode = "ShowAll"
  mainSections = ["posts"]

  # 封面设置
  [params.cover]
    hidden = false
    hiddenInList = false
    hiddenInSingle = false
    responsiveImages = true

# 字体设置
[params.assets]
  customCSS = ["css/custom.css"]

# 菜单设置
[menu]
  [[menu.main]]
    name = "Works"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
 