baseURL = 'https://ciana-linm.com/'  
languageCode = 'en-us'
title = 'Ciana Linm'
theme = 'PaperMod'

# 首页设置
[pagination]
  pagerSize = 10
summaryLength = 30

[params]
  author = "Ciana Linm"
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  homeInfoParams = false  # 关闭原主页欢迎内容
  hideSummary = false
  hideMeta = false

  # 首页显示所有文章为卡片
  homeInfoMode = "ShowAll"
  mainSections = ["posts"]


# 菜单设置
[menu]

  [[menu.main]]
    name = "Works"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

# 字体设置（系统字体：San Francisco）
[params.assets]
  customCSS = ["custom.css"]
